//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FogOilAssistant.Components.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarObject
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CarObject()
        {
            this.CarProducts = new HashSet<CarProduct>();
        }
    
        public int CarId { get; set; }
        public int CarType { get; set; }
        public int CarModel { get; set; }
        public int CarProduct { get; set; }
        public int CarBrand { get; set; }
    
        public virtual CarBrand CarBrand1 { get; set; }
        public virtual CarModel CarModel1 { get; set; }
        public virtual CarType CarType1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CarProduct> CarProducts { get; set; }
    }
}
