//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FogOilAssistant.Components.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarProduct
    {
        public int Product { get; set; }
        public int Car { get; set; }
        public int CarProductsId { get; set; }
    
        public virtual CarObject CarObject { get; set; }
        public virtual Product Product1 { get; set; }
    }
}
