//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FogOilAssistant.Components.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int UserId { get; set; }
        public double Bonus { get; set; }
        public string Password { get; set; }
        public string Nick { get; set; }
        public int Root { get; set; }
    
        public virtual Root Root1 { get; set; }
    }
}
